[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
option_as_alt = "Both"
padding.x = 2
padding.y = 2

[font]
# normal = { family = "Fira Code", style = "Regular" }
normal.family = "FiraCode Nerd Font Propo"
size = 14.0

[selection]
save_to_clipboard = true

[cursor]
style = {shape="Block" ,blinking = "On"}
