[
  "nixpkgs#hyprland"
  "nixpkgs#hypridle"
  "nixpkgs#hyprlock"
  "nixpkgs#hyprpaper"
  "nixpkgs#hyprpicker"
  "nixpkgs#xdg-desktop-portal-hyprland"
  "nixpkgs#rofi"
  "nixpkgs#clipse"
  "nixpkgs#hyprpanel"
  "nixpkgs#hyprshot"
]
