{ pkgs, ... }:

with pkgs; [
          age
          aribb24
          atuin
          awscli
          bat
          brotli
          btop
          chezmoi
          cmake
          curl
          delta
          eza
          fastfetch
          fd
          ffmpeg
          fzf
          gemini-cli
          gh
          giflib
          git
          git-extras
          glow
          go
          google-cloud-sdk
          imagemagick
          imath
          lazydocker
          lazygit
          libaom
          libdeflate
          libjpeg_turbo
          libpng
          libtiff
          libvmaf
          libwebp
          llm
          lua
          luarocks
          lz4
          mongodb-cli
          mongosh
          navi
          neovim
          nodejs
          ollama
          openssl_3
          python3
          python313Packages.ipython
          python313Packages.jupytext
          python313Packages.pip
          rbenv
          ripgrep
          sbclPackages.jpeg-turbo
          sesh
          sqlfluff
          sqlite-utils
          starship
          tectonic
          tmux
          tree-sitter
          uv
          vim
          visidata
          wget
          xz
          yazi
          zip
          zoxide
          zsh
          zstd

        ]

